// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQWaEpSUpGUAjhRmAb3h02R6S-Jexnxco',
    appId: '1:957532656057:web:6de01ec1daac8030912668',
    messagingSenderId: '957532656057',
    projectId: 'khanchuwa-b9ab4',
    authDomain: 'khanchuwa-b9ab4.firebaseapp.com',
    storageBucket: 'khanchuwa-b9ab4.appspot.com',
    measurementId: 'G-SG2K18GGJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhkoYfJ1gsZgJbQWd8lJz8Pd7OSnI658',
    appId: '1:957532656057:android:f9e550125aa1d4ff912668',
    messagingSenderId: '957532656057',
    projectId: 'khanchuwa-b9ab4',
    storageBucket: 'khanchuwa-b9ab4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCgrHFtX1OKVD-EvEfMgeAHLLPVNpwvRk',
    appId: '1:957532656057:ios:1a60212080446473912668',
    messagingSenderId: '957532656057',
    projectId: 'khanchuwa-b9ab4',
    storageBucket: 'khanchuwa-b9ab4.appspot.com',
    iosBundleId: 'com.example.day2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCgrHFtX1OKVD-EvEfMgeAHLLPVNpwvRk',
    appId: '1:957532656057:ios:1a60212080446473912668',
    messagingSenderId: '957532656057',
    projectId: 'khanchuwa-b9ab4',
    storageBucket: 'khanchuwa-b9ab4.appspot.com',
    iosBundleId: 'com.example.day2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQWaEpSUpGUAjhRmAb3h02R6S-Jexnxco',
    appId: '1:957532656057:web:e15c64b2ad511c35912668',
    messagingSenderId: '957532656057',
    projectId: 'khanchuwa-b9ab4',
    authDomain: 'khanchuwa-b9ab4.firebaseapp.com',
    storageBucket: 'khanchuwa-b9ab4.appspot.com',
    measurementId: 'G-4HMHWMHNRM',
  );
}
